# yaml-language-server: $schema=https://json.schemastore.org/taskfile.json
---
version: "3"

tasks:
  default:
    desc: Show help
    aliases: [h]
    silent: true
    cmds:
      - task -l --sort alphanumeric
  
  clean:
    desc: Clean the project
    cmds:
      - rm -rf build

  clean-hard:
    desc: Clean the project hard
    cmds:
      - task: clean
      - rm -rf node_modules
      - rm -rf .task
  
  install:
    desc: Install dependencies
    aliases: [i]
    run: once
    preconditions:
      - test -f package.json
    status:
      - test -d node_modules
    sources:
      - pnpm-lock.yaml
      - package.json
      - pnpm-workspace.yaml
    cmds:      
      - pnpm install
      - pnpm approve-builds

  build:
    desc: Build the project
    cmds:
      - task: check
      - pnpm --silent run build

  type-check:
    desc: Type check the project
    aliases: [tc]
    cmds:
      - task: install
      - pnpm --silent run type-check

  check:
    desc: Check the project
    cmds:
      - task: install
      - task: type-check